dotfiles:
  '~':
    - .bash_profile
    - .git-completion.sh
    - .git-prompt.sh
    - .gitconfig
    - .gitignore_global
    - .pylintrc
    - .shell_prompt.sh
    - .tmux.conf
    - .tmuxlinesnap
    - .vim
    - .vimrc
  ~/.pip:
    # Use the deprecated location because it works for both macOS and Linux
    - pip.conf
  /usr/local/share/luggage:
    - luggage.local
  ~/.ssh:
    - config

secrets:
  '~':
    mode: 0755
    files:
      .pypirc: 0600
  ~/.ssh:
    mode: 0700
    files:
      id_rsa: 0600
      id_rsa.pub: 0644

brew_formulae:
  - cowsay
  - enchant
  - fortune
  - tmux
  - tree

python_packages: []
  # matplotlib
  # mock
  # ndg-httpsclient
  # nose
  # numpy
  # pdbpp
  # Pillow
  # pyOpenSSL
  # pyasn1
  # pygal
  # pylint
  # pypandoc
  # pyenchant
  # "python-jss
  # requests
  # twine
  # wheel

yum_packages:
  - cowsay
  - fortune
  - freetype
  - freetype-devel
  - gcc
  - gcc-c++
  - libffi
  - openssl-devel
  - pandoc
  - python-devel
  - tmux
  - vim-common
  - vim-enhanced
