homebrew_upgrade_all_packages: True
homebrew_installed_packages:
  - chromedriver
  - cowsay
  - enchant
  - figlet
  - fortune
  - httpie
  - nmap
  - pandoc
  - phantomjs
  - postgresql
  - reattach-to-user-namespace
  - sqlite
  - tmux
  - tree

homebrew_cask_apps:
  - atom
  - evernote
  - google-earth-pro
  - google-hangouts
  - grandperspective
  - handbrake
  - iina
  - openemu
  - pacifist
  - packages
  - skitch
  - spotify
  - suspicious-package
  - vlc

python_packages:
  # matplotlib
  # mock
  # ndg-httpsclient
  # nose
  # numpy
  # pdbpp
  # Pillow
  # pyOpenSSL
  # pyasn1
  # pygal
  # pylint
  # pypandoc
  # pyenchant
  # "python-jss
  # requests
  # twine
  # wheel

yum_packages:
  - cowsay
  - fortune
  - freetype
  - freetype-devel
  - gcc
  - gcc-c++
  - libffi
  - openssl-devel
  - pandoc
  - python-devel
  - tmux
  - vim-common
  - vim-enhanced
