---
dotfiles_files:
    - dir: "~"
      files:
        - name: .bash_profile
        - name: .git-completion.sh
        - name: .git-prompt.sh
        - name: .gitconfig
        - name: .gitignore_global
        - {name: .pypirc, mode: '0600', type: secret}
        - name: .pylintrc
        - name: .shell_prompt.sh
        - name: .tmux.conf
        - name: .tmuxlinesnap
        - name: .vim
        - name: .vimrc
    - dir: ~/.pip
      files:
        - name: pip.conf
          # - dir: /usr/local/share/luggage
          #become: true
          #limit_to_platform: Darwin
          #files:
          #- name: luggage.local
          #limit_to_platform: Darwin
    - dir: ~/.ssh
      files:
        - name: config
        - {name: id_rsa, mode: '0600', type: secret}
        - {name: id_rsa.pub, mode: '0640', type: secret}

secrets_dir: "~/Dropbox/boxen"

homebrew_upgrade_all_packages: True
homebrew_taps:
  - clangen/musikcube
homebrew_installed_packages:
  - chromedriver
  - cowsay
  - dockutil
  - enchant
  - figlet
  - fortune
  - httpie
  - musikcube
  - nmap
  - pandoc
  - phantomjs
  - postgresql
  - reattach-to-user-namespace
  - sqlite
  - tmux
  - tree
homebrew_cask_apps:
  - atom
  - evernote
  - google-earth-pro
  - google-hangouts
  - grandperspective
  - handbrake
  - hopper-disassembler
  - iterm2
  - openemu
  - pacifist
  - packages
  - qlmarkdown
  - skitch
  - spotify
  - suspicious-package
  - vlc

python_packages:
  # matplotlib
  # mock
  # ndg-httpsclient
  # nose
  # numpy
  # pdbpp
  # Pillow
  # pyOpenSSL
  # pyasn1
  # pygal
  # pylint
  # pypandoc
  # pyenchant
  # "python-jss
  # requests
  # twine
  # wheel

yum_packages:
  - cowsay
  - fortune-mod
  - gcc
  - gcc-c++
  - pandoc
  - python-devel
  - tmux
  - tree
  - vim-common
  - vim-enhanced

my_apple_term_theme: SGC.terminal

dock_removals:
  - FaceTime
  - Notes
  - Reminders
  - Maps
  - Photos
  - iTunes
  - iBooks

# TODO
dock_additions:
