---
- hosts: all
  connection: local

  roles:
    - role: dotfiles

  tasks:
    - name: Git init included submodules.
      command: git submodule update --init --recursive
    - name: Install powerline fonts.
      command: fonts/install.sh

...