---
- hosts: all
  connection: local

  vars_files:
    - config.yaml

  roles:
    - role: dotfiles
    - role: geerlingguy.homebrew

  tasks:
    - name: Git init included submodules.
      command: git submodule update --init --recursive

    - name: Install powerline fonts.
      command: fonts/install.sh

    - include: tasks/yum.yml

...