---
- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Link or copy dotfiles into place.
      include_role: name=dotfiles
      tags: ['dotfiles']

    - name: Git init included submodules.
      command: git submodule update --init --recursive

    - name: Install powerline fonts.
      command: fonts/install.sh

    - name: Configure various macOS system preferences.
      include_role: name=macos
      tags: ['macos']
      when: ansible_distribution == 'MacOSX'

    - name: Add and remove things from the macOS dock.
      import_role: name=dock
      tags: ['dock']
      when: ansible_distribution == 'MacOSX'

    - name: Install packages on RHEL-based OS's
      include_tasks: tasks/yum.yml
      when: ansible_os_family == 'RedHat'
      become: True

    - name: Set up system terminal and iTerm to my liking.
      block:
        - include_tasks: tasks/iterm.yml
        - include_tasks: tasks/terminal.yml
      when: ansible_distribution == 'MacOSX'

    # Python stuff
    - name: Install the latest versions of important python packages into my site_packages rather than global.
      pip:
        name: "{{ python_packages }}"
        extra_args: --user
        state: latest
      tags: pip

    - name: Install Homebrew, Cask, tap kegs, and install desired apps.
      include_role: name=geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'
      tags: ['brew']

...
