---
- hosts: all
  connection: local

  vars_files:
    - config.yaml

  roles:
    - role: dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'
      tags: ['brew']
    - role: dock
      tags: ['dock']
      when: ansible_distribution == 'MacOSX'
    - role: macos
      tags: ['macos']
      when: ansible_distribution == 'MacOSX'

  tasks:
    - name: Git init included submodules.
      command: git submodule update --init --recursive

    - name: Install powerline fonts.
      command: fonts/install.sh

    - include: tasks/yum.yml
      when: ansible_os_family == 'RedHat'
      become: True

    - block:
        - include: tasks/iterm.yml
        - include: tasks/terminal.yml
      when: ansible_distribution == 'MacOSX'

...
