---
- name: Tell iTerm to load its settings from the dotfiles repo
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: PrefsCustomFolder
    value: "{{ playbook_dir }}"
    state: present

- name: Tell iTerm to enable loading settings
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
