---
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  always_run: yes

- name: Ensure custom Terminal profile is added.
  shell: open {{ my_apple_term_theme }}
  changed_when: false
  when: my_apple_term_theme not in terminal_theme.stdout

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' {{ my_apple_term_theme | basename | regex_replace('\.profile', '') }}
    - defaults write com.apple.terminal 'Startup Window Settings' {{ my_apple_term_theme | basename | regex_replace('\.profile', '') }}
  changed_when: false
  when: my_apple_term_theme not in terminal_theme.stdout
