---
- name: Check for terminal profile
  command: defaults read com.apple.terminal 'Window Settings'
  register: window_settings
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: open {{ my_apple_term_theme }}
  when: my_apple_term_theme | basename | regex_replace('\\.terminal', '') not in window_settings.stdout

- name: Get current Terminal profile.
  osx_defaults: 
    domain: com.apple.terminal
    key: "{{ item }}"
    value: "{{ my_apple_term_theme | basename | regex_replace('\\.terminal', '') }}"
    state: present
  register: terminal_theme
  with_items:
    - 'Default Window Settings'
    - 'Startup Window Settings'
