---
- name: Autohide Dock
  osx_defaults: 
    domain: com.apple.dock
    key: autohide
    state: present
    type: bool
    value: true
  notify: restart_dock

- name: Set dock icon sizes smaller
  osx_defaults: 
    domain: com.apple.dock
    key: tilesize
    state: present
    type: float
    value: 36
  notify: restart_dock

- name: See if removal items are present
  command: dockutil --find {{ item }} 
  with_items: "{{ dock_removals }}"
  failed_when: False
  changed_when: False
  register: dock_to_remove

- name: Remove unwanted stuff from Dock
  command: dockutil --remove {{ item.item }} --no-restart
  with_items: "{{ dock_to_remove.results }}"
  when: item.rc == 0
  notify: restart_dock
